const actions = {
    CREATE_STORE: 'CREATE_STORE',
    SELECTED_STORE: 'SELECTED_STORE',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    CHECK_AUTH: 'CHECK_AUTH',
    LOG_IN: 'LOG_IN',
    GET_STORE_DETAILS: 'GET_STORE_DETAILS',
    GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
    DELETE_PRODUCT_DATA: 'DELETE_PRODUCT_DATA',
    ADD_PRODUCT_DATA: 'ADD_PRODUCT_DATA'
} 

export default actions;