const screenNames = {
    HOME: 'HOME',
    HOMESTACK: 'HOMESTACK',
    CREATE_STORE: 'CREATE_STORE',
    VIEW_STORE: 'VIEW_STORE',
    VIEW_PRODUCT: 'VIEW_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    SETTINGS: 'SETTINGS',
    LOGIN: 'LOGIN',
    SIGNIN: 'SIGNIN',
    CREATE_STORE: 'CREATE_STORE'
};

export default screenNames